// Define la interfaz para el estado de la sesión
// export interface SessionState {
//     token: string;
//     name: string;
//   }

// export interface UserState {
//     name: string;
// }

// Generated by https://quicktype.io

export interface UserState {
  id:       number;
  name:     string;
  username: string;
  email:    string;
  address:  Address | null;
  phone:    string;
  website:  string;
  company:  Company | null;
}

export interface Address {
  street:  string;
  suite:   string;
  city:    string;
  zipcode: string;
  geo:     Geo;
}

export interface Geo {
  lat: string;
  lng: string;
}

export interface Company {
  name:        string;
  catchPhrase: string;
  bs:          string;
}
